---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: euro-2020-certificate
  namespace: gke-system
spec:
  domains:
    - euro-2020.oliviervg.com

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: euro-2020-ingress
  namespace: gke-system
  annotations:
    kubernetes.io/ingress.global-static-ip-name: euro-2020
    kubernetes.io/ingress.allow-http: "false"
    networking.gke.io/managed-certificates: euro-2020-certificate
spec:
  backend:
    serviceName: istio-ingress
    servicePort: 80
